GET http://localhost:5132/todos/1

###
# POST http://localhost:5132/todos
# content-type: application/json

# {
#     "id":7,
#     "activity":"Learn Java",
#     "schedule": "2024-12-31",
#     "isCompleted": false
# }


